version: "3.7"

services:
  web:
    build: .
    volumes:
      - static:/static
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static:
