# Generated by Django 3.1.6 on 2021-03-05 05:52

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique_for_date='created')),
                ('image', models.ImageField(upload_to='media')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
