# Generated by Django 3.1.6 on 2021-03-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
